spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/checkpol}
    username: ${SPRING_DATASOURCE_USERNAME:checkpol_user}
    password: ${SPRING_DATASOURCE_PASSWORD:checkpol_dev_password}
    driver-class-name: org.postgresql.Driver

checkpol:
  ses:
    ws:
      url: ${CHECKPOL_SES_WS_URL:https://hospedajes.pre-ses.mir.es/hospedajes-web/ws/v1/comunicacion}
